addons:
  ssh_known_hosts: uhyohyo.net
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules

script: npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_fc30aa7dfe92_key -iv $encrypted_fc30aa7dfe92_iv -in ./deploy/travisci.key -out /tmp/deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy-key
  - ssh-add /tmp/deploy-key

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -cr --delete-after --quiet -e "ssh -p $DEPLOY_PORT" $TRAVIS_BUILD_DIR/out $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    on:
      branch: master

